name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Windows
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      SolutionName: Finmer.sln
      Configuration: ${{ matrix.configuration }}
      CLIPath: .\Finmer.Editor.CLI\bin\${{ matrix.configuration }}\Finmer.Editor.CLI.exe

    steps:
    # Download repository
    - name: Checkout
      uses: actions/checkout@v4

    # Add MSBuild to the PATH
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Build all executables
    - name: Restore packages
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration
    - name: Build solution
      run: msbuild $env:SolutionName /p:Configuration=$env:Configuration

    # Build the game content to validate project file integrity
    - name: Pack Core module
      run: ${{env.CLIPath}} pack .\Modules\Projects\Core\Core.fnproj Core.furball

    # Load content files to validate deserialization logic
    - name: Module load check
      run: |
        ${{env.CLIPath}} show Core.furball
        ${{env.CLIPath}} show .\Modules\Projects\Tests\Format19.furball
        ${{env.CLIPath}} show .\Modules\Projects\Tests\Format20.furball
